# Generated by Django 3.2.4 on 2023-11-21 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('idRegistro', models.IntegerField(db_column='idRegistro', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=100)),
                ('apellido', models.CharField(db_column='apellido', max_length=100)),
                ('correo', models.EmailField(db_column='correo', max_length=254)),
                ('password', models.CharField(db_column='password', max_length=100)),
                ('confirmpassword', models.CharField(db_column='confirmpassword', max_length=100)),
            ],
            options={
                'db_table': 'Usuarios',
            },
        ),
    ]
