# Generated by Django 3.2.23 on 2023-12-05 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_recipe'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='recipe',
            table='Hamburguesas',
        ),
    ]
