# Generated by Django 3.2.23 on 2023-12-09 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_recipe_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
